### ISSUE TITLE
Chat prototype - v0.3 release

### ISSUE THREAD

**Issue by epoberezkin** [simplex-chat/simplexmq#46]
- [x] e2e encryption
- [x] command authentication
- [x] include authtag inside encrypted part and pad messages for e2e #61
- [x] transport encryption #65
- [x] tcp connection management - heartbeat, detect disconnection #59
- [x] terminal editing
- [x] save messages #45
- [ ] ~~delivery notifications~~
- [x] executables in releases #76 #84
- [x] auto-subscribe to connected contacts #70
- [x] SMP protocol - align with the implementation
- [x] agent protocol - finalize
- [x] basic terminal mode #71, enforced basic mode, no utf8 support warning #77
- [x] separate DB connection per agent client #60
- [x] agent error handling and errors sent to the client #101 #102
- [x] initialize database via an absolute path, e.g. in home folder #74
- [x] deploy new server version
- [x] key serialisation format (server key files, invitation, database) #98
- [x] binary key in transport handshake #105
- [x] fix non deterministic tests #99
- [x] mitigate timing attack on SMP command signature verification
- [ ] ~~SMP server deployment - md file~~
- [x] installation instructions / script

**Comment by efim-poberezkin** [comment]
+ SMP server deployment?

**Comment by epoberezkin** [comment]
improve PING/PONG to be independent and sent over irregular random intervals depending on other traffic by both client and server.
- PING - sent by client, no response expected
- PONG - sent by server, no correlation ID
